Try one of those by name or a sequence number
  0 "<&alloc::vec::Vec<ecs::param::ParamDesc> as core::fmt::Debug>::fmt" [19]
  1 "<&ecs::param::ParamDesc as core::fmt::Debug>::fmt" [19]
  2 "<&ecs::param::QueryDesc as core::fmt::Debug>::fmt" [19]
  3 "<&ecs::query::Query<&tests::Health> as core::iter::traits::collect::IntoIterator>::into_iter" [19]
  4 "<&smallvec::SmallVec<[ecs::param::QueryDesc; 3]> as core::fmt::Debug>::fmt" [19]
  5 "<&tests::Health as ecs::query::QueryBundle>::archetype" [132]
  6 "<&tests::Health as ecs::query::QueryBundle>::desc" [287]
  7 "<&tests::Health as ecs::query::QueryBundle>::iter" [33]
  8 "<(ecs::query::Query<&tests::Health>, ecs::local::Local<usize>) as ecs::param::ParamBundle>::init" [73]
  9 "<<hashbrown::raw::RawTable<(ecs::archetype::ArchetypeComponents, ecs::table::Table)>>::find<<hashbrown::map::HashMap<ecs::archetype::ArchetypeComponents, ecs::table::Table, std::hash::random::RandomState>>::rustc_entry::{closure#0}>::{closure#0} as core::ops::function::FnOnce<(usize,)>>::call_once" [59]
 10 "<<hashbrown::raw::RawTable<(ecs::archetype::ArchetypeComponents, ecs::table::Table)>>::find<<hashbrown::map::HashMap<ecs::archetype::ArchetypeComponents, ecs::table::Table, std::hash::random::RandomState>>::rustc_entry::{closure#0}>::{closure#0} as core::ops::function::FnOnce<(usize,)>>::call_once::{shim:vtable#0}" [22]
 11 "<<hashbrown::raw::RawTable<(ecs::archetype::ArchetypeComponents, ecs::table::Table)>>::reserve_rehash<hashbrown::map::make_hasher<ecs::archetype::ArchetypeComponents, ecs::table::Table, std::hash::random::RandomState>::{closure#0}>::{closure#0} as core::ops::function::FnOnce<(&mut hashbrown::raw::RawTableInner, usize)>>::call_once" [59]
 12 "<<hashbrown::raw::RawTable<(ecs::archetype::ArchetypeComponents, ecs::table::Table)>>::reserve_rehash<hashbrown::map::make_hasher<ecs::archetype::ArchetypeComponents, ecs::table::Table, std::hash::random::RandomState>::{closure#0}>::{closure#0} as core::ops::function::FnOnce<(&mut hashbrown::raw::RawTableInner, usize)>>::call_once::{shim:vtable#0}" [23]
 13 "<<hashbrown::raw::RawTable<(ecs::archetype::ArchetypeComponents, ecs::table::Table)>>::reserve_rehash<hashbrown::map::make_hasher<ecs::archetype::ArchetypeComponents, ecs::table::Table, std::hash::random::RandomState>::{closure#0}>::{closure#1} as core::ops::function::FnOnce<(*mut u8,)>>::call_once" [54]
 14 "<<hashbrown::raw::RawTable<(ecs::component::ComponentId, ecs::table::Column)>>::find_or_find_insert_index<hashbrown::map::equivalent_key<ecs::component::ComponentId, ecs::component::ComponentId, ecs::table::Column>::{closure#0}, hashbrown::map::make_hasher<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState>::{closure#0}>::{closure#0} as core::ops::function::FnOnce<(usize,)>>::call_once" [59]
 15 "<<hashbrown::raw::RawTable<(ecs::component::ComponentId, ecs::table::Column)>>::find_or_find_insert_index<hashbrown::map::equivalent_key<ecs::component::ComponentId, ecs::component::ComponentId, ecs::table::Column>::{closure#0}, hashbrown::map::make_hasher<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState>::{closure#0}>::{closure#0} as core::ops::function::FnOnce<(usize,)>>::call_once::{shim:vtable#0}" [22]
 16 "<<hashbrown::raw::RawTable<(ecs::component::ComponentId, ecs::table::Column)>>::reserve_rehash<hashbrown::map::make_hasher<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState>::{closure#0}>::{closure#0} as core::ops::function::FnOnce<(&mut hashbrown::raw::RawTableInner, usize)>>::call_once" [59]
 17 "<<hashbrown::raw::RawTable<(ecs::component::ComponentId, ecs::table::Column)>>::reserve_rehash<hashbrown::map::make_hasher<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState>::{closure#0}>::{closure#0} as core::ops::function::FnOnce<(&mut hashbrown::raw::RawTableInner, usize)>>::call_once::{shim:vtable#0}" [22]
 18 "<<hashbrown::raw::RawTable<(ecs::component::ComponentId, ecs::table::Column)>>::reserve_rehash<hashbrown::map::make_hasher<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState>::{closure#0}>::{closure#1} as core::ops::function::FnOnce<(*mut u8,)>>::call_once" [54]
 19 "<[(ecs::component::ComponentId, ecs::table::Column); 1] as core::iter::traits::collect::IntoIterator>::into_iter" [52]
 20 "<[core::mem::maybe_uninit::MaybeUninit<(ecs::component::ComponentId, ecs::table::Column)>; 1] as core::array::iter::iter_inner::PartialDrop>::partial_drop" [29]
 21 "<[core::mem::maybe_uninit::MaybeUninit<(ecs::component::ComponentId, ecs::table::Column)>] as core::array::iter::iter_inner::PartialDrop>::partial_drop" [69]
 22 "<[ecs::param::ParamDesc] as core::fmt::Debug>::fmt" [66]
 23 "<[ecs::param::QueryDesc]>::iter" [20]
 24 "<alloc::boxed::Box<[ecs::component::ComponentId]> as core::clone::Clone>::clone" [42]
 25 "<alloc::boxed::Box<core::mem::maybe_uninit::MaybeUninit<[ecs::param::ParamDesc; 2]>> as core::ops::drop::Drop>::drop" [86]
 26 "<alloc::boxed::Box<core::mem::maybe_uninit::MaybeUninit<[ecs::param::QueryDesc; 1]>> as core::ops::drop::Drop>::drop" [86]
 27 "<alloc::boxed::Box<dyn ecs::system::System> as core::ops::drop::Drop>::drop" [92]
 28 "<alloc::raw_vec::RawVec<alloc::boxed::Box<dyn ecs::system::System>> as core::ops::drop::Drop>::drop" [21]
 29 "<alloc::raw_vec::RawVec<alloc::boxed::Box<dyn ecs::system::System>>>::grow_one" [49]
 30 "<alloc::raw_vec::RawVec<ecs::component::ComponentId> as core::ops::drop::Drop>::drop" [21]
 31 "<alloc::raw_vec::RawVec<ecs::entity::EntityId>>::grow_one" [49]
 32 "<alloc::raw_vec::RawVec<ecs::param::ParamDesc> as core::ops::drop::Drop>::drop" [21]
 33 "<alloc::vec::Vec<alloc::boxed::Box<dyn ecs::system::System>> as core::ops::drop::Drop>::drop" [32]
 34 "<alloc::vec::Vec<alloc::boxed::Box<dyn ecs::system::System>>>::push" [21]
 35 "<alloc::vec::Vec<alloc::boxed::Box<dyn ecs::system::System>>>::push_mut" [127]
 36 "<alloc::vec::Vec<ecs::component::ComponentId> as core::ops::drop::Drop>::drop" [29]
 37 "<alloc::vec::Vec<ecs::component::ComponentId>>::into_boxed_slice" [240]
 38 "<alloc::vec::Vec<ecs::entity::EntityId>>::new" [14]
 39 "<alloc::vec::Vec<ecs::entity::EntityId>>::push" [20]
 40 "<alloc::vec::Vec<ecs::entity::EntityId>>::push_mut" [121]
 41 "<alloc::vec::Vec<ecs::param::ParamDesc> as core::fmt::Debug>::fmt" [34]
 42 "<alloc::vec::Vec<ecs::param::ParamDesc> as core::ops::drop::Drop>::drop" [32]
 43 "<core::array::iter::IntoIter<(ecs::component::ComponentId, ecs::table::Column), 1> as core::iter::traits::iterator::Iterator>::fold::<(), core::iter::traits::iterator::Iterator::for_each::call<(ecs::component::ComponentId, ecs::table::Column), <hashbrown::map::HashMap<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState> as core::iter::traits::collect::Extend<(ecs::component::ComponentId, ecs::table::Column)>>::extend<[(ecs::component::ComponentId, ecs::table::Column); 1]>::{closure#0}>::{closure#0}>" [89]
 44 "<core::array::iter::IntoIter<(ecs::component::ComponentId, ecs::table::Column), 1> as core::iter::traits::iterator::Iterator>::for_each::<<hashbrown::map::HashMap<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState> as core::iter::traits::collect::Extend<(ecs::component::ComponentId, ecs::table::Column)>>::extend<[(ecs::component::ComponentId, ecs::table::Column); 1]>::{closure#0}>" [21]
 45 "<core::array::iter::IntoIter<(ecs::component::ComponentId, ecs::table::Column), 1> as core::iter::traits::iterator::Iterator>::size_hint" [30]
 46 "<core::array::iter::IntoIter<(ecs::component::ComponentId, ecs::table::Column), 1> as core::ops::drop::Drop>::drop" [23]
 47 "<core::array::iter::iter_inner::PolymorphicIter<[core::mem::maybe_uninit::MaybeUninit<(ecs::component::ComponentId, ecs::table::Column)>; 1]> as core::ops::drop::Drop>::drop" [30]
 48 "<core::array::iter::iter_inner::PolymorphicIter<[core::mem::maybe_uninit::MaybeUninit<(ecs::component::ComponentId, ecs::table::Column)>]>>::try_fold::<(), <core::ops::try_trait::NeverShortCircuit<()>>::wrap_mut_2<(), (ecs::component::ComponentId, ecs::table::Column), core::iter::traits::iterator::Iterator::for_each::call<(ecs::component::ComponentId, ecs::table::Column), <hashbrown::map::HashMap<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState> as core::iter::traits::collect::Extend<(ecs::component::ComponentId, ecs::table::Column)>>::extend<[(ecs::component::ComponentId, ecs::table::Column); 1]>::{closure#0}>::{closure#0}>::{closure#0}, core::ops::try_trait::NeverShortCircuit<()>>::{closure#0}" [70]
 49 "<core::fmt::builders::DebugList>::entries::<&ecs::param::ParamDesc, core::slice::iter::Iter<ecs::param::ParamDesc>>" [127]
 50 "<core::fmt::builders::DebugList>::entries::<&ecs::param::QueryDesc, core::slice::iter::Iter<ecs::param::QueryDesc>>" [126]
 51 "<core::fmt::rt::Argument>::new_debug::<ecs::system::SystemDescriptor>" [26]
 52 "<core::ops::index_range::IndexRange as core::iter::traits::iterator::Iterator>::try_fold::<(), <core::array::iter::iter_inner::PolymorphicIter<[core::mem::maybe_uninit::MaybeUninit<(ecs::component::ComponentId, ecs::table::Column)>]>>::try_fold<(), <core::ops::try_trait::NeverShortCircuit<()>>::wrap_mut_2<(), (ecs::component::ComponentId, ecs::table::Column), core::iter::traits::iterator::Iterator::for_each::call<(ecs::component::ComponentId, ecs::table::Column), <hashbrown::map::HashMap<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState> as core::iter::traits::collect::Extend<(ecs::component::ComponentId, ecs::table::Column)>>::extend<[(ecs::component::ComponentId, ecs::table::Column); 1]>::{closure#0}>::{closure#0}>::{closure#0}, core::ops::try_trait::NeverShortCircuit<()>>::{closure#0}, core::ops::try_trait::NeverShortCircuit<()>>" [163]
 53 "<core::ops::try_trait::NeverShortCircuit<()>>::wrap_mut_2::<(), (ecs::component::ComponentId, ecs::table::Column), core::iter::traits::iterator::Iterator::for_each::call<(ecs::component::ComponentId, ecs::table::Column), <hashbrown::map::HashMap<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState> as core::iter::traits::collect::Extend<(ecs::component::ComponentId, ecs::table::Column)>>::extend<[(ecs::component::ComponentId, ecs::table::Column); 1]>::{closure#0}>::{closure#0}>::{closure#0}" [24]
 54 "<core::option::Option<&ecs::table::Table>>::map::<ecs::table::ColumnIter<tests::Health>, <ecs::query::QueryIter<&tests::Health, ()> as core::convert::From<&ecs::query::Query<&tests::Health>>>::from::{closure#0}>" [42]
 55 "<core::option::Option<&mut ecs::table::Column>>::expect" [39]
 56 "<core::option::Option<&mut ecs::table::ColumnIter<tests::Health>> as core::ops::try_trait::Try>::branch" [38]
 57 "<core::option::Option<ecs::table::ColumnIter<tests::Health>>>::as_mut" [39]
 58 "<core::slice::iter::Iter<ecs::param::ParamDesc> as core::iter::traits::collect::IntoIterator>::into_iter" [18]
 59 "<core::slice::iter::Iter<ecs::param::ParamDesc> as core::iter::traits::iterator::Iterator>::next" [70]
 60 "<core::slice::iter::Iter<ecs::param::QueryDesc> as core::iter::traits::collect::IntoIterator>::into_iter" [18]
 61 "<core::slice::iter::Iter<ecs::param::QueryDesc> as core::iter::traits::iterator::Iterator>::next" [69]
 62 "<core::slice::iter::Iter<ecs::param::QueryDesc>>::new" [49]
 63 "<ecs::archetype::ArchetypeComponents as core::clone::Clone>::clone" [19]
 64 "<ecs::archetype::ArchetypeComponents as core::cmp::PartialEq>::eq" [20]
 65 "<ecs::archetype::Archetypes>::insert::<tests::Health>" [155]
 66 "<ecs::archetype::Archetypes>::insert::<tests::Health>::{closure#0}" [20]
 67 "<ecs::component::ComponentId as <[_]>::to_vec_in::ConvertVec>::to_vec::<alloc::alloc::Global>" [123]
 68 "<ecs::component::ComponentId>::of::<tests::Health>" [27]
 69 "<ecs::local::Local<usize> as core::ops::deref::Deref>::deref" [18]
 70 "<ecs::local::Local<usize> as core::ops::deref::DerefMut>::deref_mut" [18]
 71 "<ecs::local::Local<usize> as ecs::param::Param>::desc" [11]
 72 "<ecs::local::Local<usize> as ecs::param::Param>::fetch::<ecs::sealed::Sealer>" [19]
 73 "<ecs::local::Local<usize> as ecs::param::Param>::init" [7]
 74 "<ecs::param::ParamDesc as core::fmt::Debug>::fmt" [70]
 75 "<ecs::param::QueryDesc as core::fmt::Debug>::fmt" [46]
 76 "<ecs::param::QueryType as core::fmt::Debug>::fmt" [48]
 77 "<ecs::query::Query<&tests::Health> as ecs::param::Param>::desc" [25]
 78 "<ecs::query::Query<&tests::Health> as ecs::param::Param>::fetch::<ecs::sealed::Sealer>" [21]
 79 "<ecs::query::Query<&tests::Health> as ecs::param::Param>::init" [18]
 80 "<ecs::query::Query<&tests::Health>>::new" [41]
 81 "<ecs::query::QueryIter<&tests::Health, ()> as core::convert::From<&ecs::query::Query<&tests::Health>>>::from" [29]
 82 "<ecs::query::QueryIter<&tests::Health, ()> as core::convert::From<&ecs::query::Query<&tests::Health>>>::from::{closure#0}" [19]
 83 "<ecs::query::QueryIter<&tests::Health, ()> as core::iter::traits::iterator::Iterator>::next" [42]
 84 "<ecs::system::FnContainer<(ecs::query::Query<&tests::Health>, ecs::local::Local<usize>), tests::system1> as ecs::system::System>::call" [94]
 85 "<ecs::system::FnContainer<(ecs::query::Query<&tests::Health>, ecs::local::Local<usize>), tests::system1> as ecs::system::System>::desc" [209]
 86 "<ecs::system::SystemDescriptor as core::fmt::Debug>::fmt" [65]
 87 "<ecs::system::Systems>::push::<(ecs::query::Query<&tests::Health>, ecs::local::Local<usize>), tests::system1>" [164]
 88 "<ecs::table::Column>::get::<tests::Health>" [134]
 89 "<ecs::table::Column>::new::<tests::Health>" [161]
 90 "<ecs::table::Column>::push::<tests::Health>" [459]
 91 "<ecs::table::ColumnIter<tests::Health> as core::iter::traits::iterator::Iterator>::next" [96]
 92 "<ecs::table::ColumnIter<tests::Health> as core::ops::drop::Drop>::drop" [21]
 93 "<ecs::table::ColumnIter<tests::Health>>::new" [23]
 94 "<ecs::table::Table>::insert::<tests::Health>" [86]
 95 "<ecs::table::Table>::new::<tests::Health>" [133]
 96 "<ecs::world::World>::spawn::<tests::Health>" [88]
 97 "<hashbrown::map::HashMap<ecs::archetype::ArchetypeComponents, ecs::table::Table, std::hash::random::RandomState>>::rustc_entry" [152]
 98 "<hashbrown::map::HashMap<ecs::archetype::ArchetypeComponents, ecs::table::Table, std::hash::random::RandomState>>::rustc_entry::{closure#0}" [25]
 99 "<hashbrown::map::HashMap<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState> as core::iter::traits::collect::Extend<(ecs::component::ComponentId, ecs::table::Column)>>::extend::<[(ecs::component::ComponentId, ecs::table::Column); 1]>" [149]
100 "<hashbrown::map::HashMap<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState> as core::iter::traits::collect::Extend<(ecs::component::ComponentId, ecs::table::Column)>>::extend::<[(ecs::component::ComponentId, ecs::table::Column); 1]>::{closure#0}" [38]
101 "<hashbrown::map::HashMap<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState>>::get_mut::<ecs::component::ComponentId>" [126]
102 "<hashbrown::map::HashMap<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState>>::insert" [244]
103 "<hashbrown::raw::RawTable<(ecs::archetype::ArchetypeComponents, ecs::table::Table)>>::find::<<hashbrown::map::HashMap<ecs::archetype::ArchetypeComponents, ecs::table::Table, std::hash::random::RandomState>>::rustc_entry::{closure#0}>" [395]
104 "<hashbrown::raw::RawTable<(ecs::archetype::ArchetypeComponents, ecs::table::Table)>>::find::<<hashbrown::map::HashMap<ecs::archetype::ArchetypeComponents, ecs::table::Table, std::hash::random::RandomState>>::rustc_entry::{closure#0}>::{closure#0}" [96]
105 "<hashbrown::raw::RawTable<(ecs::archetype::ArchetypeComponents, ecs::table::Table)>>::insert_no_grow" [193]
106 "<hashbrown::raw::RawTable<(ecs::archetype::ArchetypeComponents, ecs::table::Table)>>::reserve::<hashbrown::map::make_hasher<ecs::archetype::ArchetypeComponents, ecs::table::Table, std::hash::random::RandomState>::{closure#0}>" [83]
107 "<hashbrown::raw::RawTable<(ecs::archetype::ArchetypeComponents, ecs::table::Table)>>::reserve_rehash::<hashbrown::map::make_hasher<ecs::archetype::ArchetypeComponents, ecs::table::Table, std::hash::random::RandomState>::{closure#0}>" [843]
108 "<hashbrown::raw::RawTable<(ecs::archetype::ArchetypeComponents, ecs::table::Table)>>::reserve_rehash::<hashbrown::map::make_hasher<ecs::archetype::ArchetypeComponents, ecs::table::Table, std::hash::random::RandomState>::{closure#0}>::{closure#0}" [92]
109 "<hashbrown::raw::RawTable<(ecs::archetype::ArchetypeComponents, ecs::table::Table)>>::reserve_rehash::<hashbrown::map::make_hasher<ecs::archetype::ArchetypeComponents, ecs::table::Table, std::hash::random::RandomState>::{closure#0}>::{closure#1}" [21]
110 "<hashbrown::raw::RawTable<(ecs::component::ComponentId, ecs::table::Column)>>::find_or_find_insert_index::<hashbrown::map::equivalent_key<ecs::component::ComponentId, ecs::component::ComponentId, ecs::table::Column>::{closure#0}, hashbrown::map::make_hasher<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState>::{closure#0}>" [134]
111 "<hashbrown::raw::RawTable<(ecs::component::ComponentId, ecs::table::Column)>>::find_or_find_insert_index::<hashbrown::map::equivalent_key<ecs::component::ComponentId, ecs::component::ComponentId, ecs::table::Column>::{closure#0}, hashbrown::map::make_hasher<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState>::{closure#0}>::{closure#0}" [96]
112 "<hashbrown::raw::RawTable<(ecs::component::ComponentId, ecs::table::Column)>>::insert_tagged_at_index" [151]
113 "<hashbrown::raw::RawTable<(ecs::component::ComponentId, ecs::table::Column)>>::reserve::<hashbrown::map::make_hasher<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState>::{closure#0}>" [83]
114 "<hashbrown::raw::RawTable<(ecs::component::ComponentId, ecs::table::Column)>>::reserve_rehash::<hashbrown::map::make_hasher<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState>::{closure#0}>" [833]
115 "<hashbrown::raw::RawTable<(ecs::component::ComponentId, ecs::table::Column)>>::reserve_rehash::<hashbrown::map::make_hasher<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState>::{closure#0}>::{closure#0}" [92]
116 "<hashbrown::raw::RawTable<(ecs::component::ComponentId, ecs::table::Column)>>::reserve_rehash::<hashbrown::map::make_hasher<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState>::{closure#0}>::{closure#1}" [21]
117 "<smallvec::ConstNonNull<ecs::param::QueryDesc>>::as_ptr" [19]
118 "<smallvec::SmallVec<[ecs::param::QueryDesc; 3]> as core::fmt::Debug>::fmt" [33]
119 "<smallvec::SmallVec<[ecs::param::QueryDesc; 3]> as core::ops::deref::Deref>::deref" [34]
120 "<std::collections::hash::map::Entry<ecs::archetype::ArchetypeComponents, ecs::table::Table>>::or_insert_with::<<ecs::archetype::Archetypes>::insert<tests::Health>::{closure#0}>" [204]
121 "<std::collections::hash::map::HashMap<ecs::archetype::ArchetypeComponents, ecs::table::Table>>::entry" [79]
122 "<std::collections::hash::map::HashMap<ecs::component::ComponentId, ecs::table::Column> as core::convert::From<[(ecs::component::ComponentId, ecs::table::Column); 1]>>::from" [21]
123 "<std::collections::hash::map::HashMap<ecs::component::ComponentId, ecs::table::Column> as core::iter::traits::collect::FromIterator<(ecs::component::ComponentId, ecs::table::Column)>>::from_iter::<[(ecs::component::ComponentId, ecs::table::Column); 1]>" [166]
124 "<std::collections::hash::map::HashMap<ecs::component::ComponentId, ecs::table::Column>>::get_mut::<ecs::component::ComponentId>" [20]
125 "<tests::Health as ecs::spawn::ComponentBundle>::components" [133]
126 "<tests::Health as ecs::spawn::ComponentBundle>::insert_into" [101]
127 "<tests::Health as ecs::spawn::ComponentBundle>::new_table_map" [44]
128 "<tests::system1 as core::ops::function::Fn<(ecs::query::Query<&tests::Health>, ecs::local::Local<usize>)>>::call" [23]
129 "<tests::system1 as ecs::system::IntoSystem<(ecs::query::Query<&tests::Health>, ecs::local::Local<usize>)>>::into_system" [141]
130 "<tests::system1 as ecs::system::ParametrizedSystem<(ecs::query::Query<&tests::Health>, ecs::local::Local<usize>)>>::call" [110]
131 "<tests::system1 as ecs::system::ParametrizedSystem<(ecs::query::Query<&tests::Health>, ecs::local::Local<usize>)>>::into_container" [131]
132 "core::iter::traits::iterator::Iterator::for_each::call::<(ecs::component::ComponentId, ecs::table::Column), <hashbrown::map::HashMap<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState> as core::iter::traits::collect::Extend<(ecs::component::ComponentId, ecs::table::Column)>>::extend<[(ecs::component::ComponentId, ecs::table::Column); 1]>::{closure#0}>::{closure#0}" [24]
133 "core::mem::drop::<ecs::util::debug::RwGuard<true>>" [19]
134 "core::ptr::drop_in_place::<(ecs::query::QueryState, ecs::local::LocalState<usize>)>" [17]
135 "core::ptr::drop_in_place::<[(ecs::component::ComponentId, ecs::table::Column); 1]>" [78]
136 "core::ptr::drop_in_place::<[(ecs::component::ComponentId, ecs::table::Column)]>" [82]
137 "core::ptr::drop_in_place::<[alloc::boxed::Box<dyn ecs::system::System>]>" [84]
138 "core::ptr::drop_in_place::<[ecs::param::ParamDesc]>" [82]
139 "core::ptr::drop_in_place::<alloc::boxed::Box<core::mem::maybe_uninit::MaybeUninit<[ecs::param::ParamDesc; 2]>>>" [17]
140 "core::ptr::drop_in_place::<alloc::boxed::Box<core::mem::maybe_uninit::MaybeUninit<[ecs::param::QueryDesc; 1]>>>" [17]
141 "core::ptr::drop_in_place::<alloc::boxed::Box<dyn ecs::system::System>>" [68]
142 "core::ptr::drop_in_place::<alloc::raw_vec::RawVec<alloc::boxed::Box<dyn ecs::system::System>>>" [17]
143 "core::ptr::drop_in_place::<alloc::raw_vec::RawVec<ecs::component::ComponentId>>" [17]
144 "core::ptr::drop_in_place::<alloc::raw_vec::RawVec<ecs::param::ParamDesc>>" [17]
145 "core::ptr::drop_in_place::<alloc::vec::Vec<alloc::boxed::Box<dyn ecs::system::System>>>" [59]
146 "core::ptr::drop_in_place::<alloc::vec::Vec<ecs::component::ComponentId>>" [59]
147 "core::ptr::drop_in_place::<alloc::vec::Vec<ecs::param::ParamDesc>>" [59]
148 "core::ptr::drop_in_place::<core::array::iter::IntoIter<(ecs::component::ComponentId, ecs::table::Column), 1>>" [17]
149 "core::ptr::drop_in_place::<core::array::iter::iter_inner::PolymorphicIter<[core::mem::maybe_uninit::MaybeUninit<(ecs::component::ComponentId, ecs::table::Column)>; 1]>>" [17]
150 "core::ptr::drop_in_place::<core::cell::UnsafeCell<(ecs::query::QueryState, ecs::local::LocalState<usize>)>>" [17]
151 "core::ptr::drop_in_place::<core::option::Option<ecs::table::Column>>" [28]
152 "core::ptr::drop_in_place::<core::option::Option<ecs::table::ColumnIter<tests::Health>>>" [28]
153 "core::ptr::drop_in_place::<dyn ecs::system::System>" [26]
154 "core::ptr::drop_in_place::<ecs::param::ParamDesc>" [28]
155 "core::ptr::drop_in_place::<ecs::query::QueryIter<&tests::Health, ()>>" [17]
156 "core::ptr::drop_in_place::<ecs::query::QueryState>" [17]
157 "core::ptr::drop_in_place::<ecs::system::FnContainer<(ecs::query::Query<&tests::Health>, ecs::local::Local<usize>), tests::system1>>" [18]
158 "core::ptr::drop_in_place::<ecs::system::SystemDescriptor>" [17]
159 "core::ptr::drop_in_place::<ecs::system::Systems>" [17]
160 "core::ptr::drop_in_place::<ecs::table::ColumnIter<tests::Health>>" [17]
161 "core::ptr::drop_in_place::<ecs::world::World>" [95]
162 "core::ptr::drop_in_place::<hashbrown::rustc_entry::RustcVacantEntry<ecs::archetype::ArchetypeComponents, ecs::table::Table>>" [17]
163 "core::ptr::drop_in_place::<std::collections::hash::map::VacantEntry<ecs::archetype::ArchetypeComponents, ecs::table::Table>>" [17]
164 "core::slice::raw::from_raw_parts::<ecs::param::QueryDesc>" [30]
165 "ecs::table::drop_wrapper::<tests::Health>" [52]
166 "hashbrown::map::make_hasher::<ecs::archetype::ArchetypeComponents, ecs::table::Table, std::hash::random::RandomState>::{closure#0}" [26]
167 "hashbrown::map::make_hasher::<ecs::component::ComponentId, ecs::table::Column, std::hash::random::RandomState>::{closure#0}" [26]
